spring.application.name=backend-plannia

# Server Port Configuration
server.port=${PORT:9000}

# Spring DataSource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
# Template: jdbc:postgresql://<host>:<port>/<database>?user=<user>&password=<password>
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/planniadb?user=${DATASOURCE_USER:postgres}&password=${DATASOURCE_PASSWORD:2808}}

# Spring Data JPA Configuration
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=upc.com.pe.backendplannia.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=${JWT_SECRET: test}
authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS:7}

# Spring AI - OpenAI compatible (Ollama local)
spring.ai.openai.api-key=sk-lm-raeZmWez:SxZBzwbc29EmZ6pekjXY
spring.ai.openai.base-url=http://127.0.0.1:1234
spring.ai.openai.embedding.options.model=nomic-embed-text

# application.properties
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration